version: '2'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sg_blog_db
      MYSQL_USER: client
      MYSQL_PASSWORD: passclient
    ports:
      - "3307:3306"
    command: --init-file /sg-blog/db/init.sql
    volumes:
      - ./db/init.sql:/sg-blog/db/init.sql

  app:
    container_name: sg-blog
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/sg-blog"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: sg_blog_db
      DB_USER: root
      DB_PASSWORD: pass
      DB_HOST: db
